### ISSUE TITLE
When newly running docker on digital ocean server, login failed because of invalid type error

### ISSUE THREAD

**Issue by zainurrehman** [haiduowad/Group2SecureCodingDojo#5]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Object.exports.verifyLocalUserPassword (/home/node/app/auth.js:250:34)
    at Strategy.LocalStrategy [as _verify] (/home/node/app/auth.js:392:28)
    at Strategy.authenticate (/home/node/app/node_modules/passport-local/lib/strategy.js:90:12)
    at attempt (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
    at exports.checkCaptchaOnLogin (/home/node/app/auth.js:148:5)

**Comment by zainurrehman** [comment]
fbc41bf6a25c4579de243731a5005586eb2c1cb7
